name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Ensure this matches your Node.js version

    - run: npm ci

    - run: npm run build
    - run: npm run test # Optional, if you have tests
